import Head from "next/head";
import { Inter } from "next/font/google";

import CarouselImage from "@/components/HomeComponent/CarouselImage";
import Events from "@/components/HomeComponent/Events";

import dynamic from "next/dynamic";

// const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const MapWithNoSSR = dynamic(() => import("../components/HomeComponent/Location"), {
    ssr: false,
  });

  return (
    <>
      <Head>
        <title>IASD Oxford - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CarouselImage />
      <Events />
      <div>
        <h1 className="text-[26pt] text-center mb-[2%] underline-offset-4 underline decoration-[#127369]">Onde estamos</h1>
        <MapWithNoSSR />
      </div>
    </>
  );
}
